version: '3.9'

services:
  db:
    image: postgres:16.1-alpine
    container_name: db
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./docker/pg/data:/var/lib/postgresql/data
      - ./docker/pg/tmp:/tmp
    env_file:
      - .env
    networks:
      - structure_network

  redis:
    image: redis
    restart: always
    container_name: redis
    env_file:
      - .env
    volumes:
      - './docker/redis/data:/var/lib/redis/data/'
    command: --port 6379
    ports:
    - ${REDIS_PORT}:6379
    networks:
      - structure_network

  celery:
    container_name: structure_celery
    env_file:
      - .env
    build: ../structure
    command: celery -A common worker -l info
    volumes:
      - celery_worker:/var/lib/celery/data/
    depends_on:
      - db
      - redis
    networks:
      - structure_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: structure_web
    command: uvicorn structure.main:app --host 0.0.0.0 --port 8000
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - structure_network

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:8000"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      - web
      - db
      - redis
    networks:
      - structure_network

networks:
  structure_network:

volumes:
  static_value:
  media_value:
  celery_worker:
